#!/usr/bin/env bash

# Run the metrics.plotting tool
#  Note that the plots are generated by the gather_metrics.sh unless it has been changed to disable them
#  Note also that some of the plotting features of the containerized tools are disabled until we
#     solve issues with excessive memory usage in a linux container

# before using:
#   (you probably need to be OFF the VPN to do this)
# authenticate with docker registry (currently hosted by LeadingAgile)
#   Using azure cli (brew install azure-cli)
#       az login
#       az acr login --name leadingagilestudios
# get the docker image
#   docker pull leadingagilestudios.azurecr.io/analysis/gather:0.2.0


REPO_NAME="$1"
RUN_NAME="$2"

[[ -z "${REPO_NAME}" ]] && { echo "Must specify a repository name"; exit 1; }
[[ -z "${RUN_NAME}" ]] && { echo "Must specify a run name"; exit 1; }

PROJECTS_FOLDER="${3:-"$HOME/projects/ford_shopbuy"}"
REPORTS_FOLDER="${4:-"$HOME/projects/reports"}"


 docker run -it --rm \
    -v "${PROJECTS_FOLDER}":/opt/repos \
    -v "${REPORTS_FOLDER}":/opt/output \
    leadingagilestudios.azurecr.io/analysis/gather:0.2.0 plotting \
   --run-folder "/opt/output/${REPO_NAME}/${RUN_NAME}" \
   --debug